# Generated by Django 4.0.7 on 2022-08-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover_photo', models.ImageField(upload_to='document/cover/')),
                ('file', models.FileField(upload_to='document/file/')),
            ],
        ),
    ]
