# Generated by Django 4.0.7 on 2022-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('kindergarten', "Bog'cha"), ('school', 'Maktab')], default='kindergarten', max_length=32),
            preserve_default=False,
        ),
    ]
