products = "Tovarlar"
location = "Joylashuv"
phone_number = "Telefon raqam"
telegram_channel = "Telegram kanal"
website = "Veb sayt"
school = "Maktab"
kindergarten = "Bog'cha"
BACK = "Ortga"
all_schools = "Barcha maktablar {}"
all_kindergartens = "Barcha bog'chalar {}"
documents = "Xujjatlar ({})"
placates = "Plakatlar ({})"
lepbuks = "Lepbuklar ({})"
buklets = "Bukletlar ({})"
imgs = "Suratlar ({})"
masks = "Maska (niqob) ({})"
materials = "Did. materiallar ({})"
decorations = "Bezak (oformleniya) ({})"
makets = "Maket va o'yinlar ({})"
MENU = "menu"


